// choose another course, or else this is too long

export const math321 = [
	{
		tier_eighty_five: 5,
		tier_ninety: 2,
		Title: "",
		Section: "201",
		Detail: "",
		tier_seventy_two: 0,
		Other: 1,
		Low: 50,
		tier_sixty_four: 4,
		id: 3929,
		tier_sixty_eight: 4,
		tier_zero: 0,
		tier_seventy_six: 2,
		tier_thirty: 0,
		tier_fifty: 2,
		Professor: "",
		Audit: 0,
		tier_g_fifty: 0,
		tier_forty: 0,
		Withdrew: 1,
		Year: "",
		tier_twenty: 0,
		Stddev: 13.53,
		Enrolled: 29,
		tier_fifty_five: 5,
		tier_eighty: 2,
		tier_sixty: 1,
		tier_ten: 0,
		High: 96,
		Course: "321",
		Session: "w",
		Pass: 27,
		Fail: 0,
		Avg: 70.85,
		Campus: "ubc",
		Subject: "math",
	},
];
