// choose another course, or else this is too long

export const math120 = [
	/* 	{
		tier_eighty_five: 3,
		tier_ninety: 10,
		Title: "differ calculus",
		Section: "101",
		Detail: "",
		tier_seventy_two: 4,
		Other: 0,
		Low: 54,
		tier_sixty_four: 1,
		id: 3797,
		tier_sixty_eight: 3,
		tier_zero: 0,
		tier_seventy_six: 0,
		tier_thirty: 0,
		tier_fifty: 3,
		Professor: "bluman, george w",
		Audit: 0,
		tier_g_fifty: 0,
		tier_forty: 0,
		Withdrew: 1,
		Year: "2011",
		tier_twenty: 0,
		Stddev: 13.09,
		Enrolled: 35,
		tier_fifty_five: 1,
		tier_eighty: 9,
		tier_sixty: 0,
		tier_ten: 0,
		High: 100,
		Course: "120",
		Session: "w",
		Pass: 34,
		Fail: 0,
		Avg: 79.71,
		Campus: "ubc",
		Subject: "math",
	},
	{
		tier_eighty_five: 3,
		tier_ninety: 10,
		Title: "differ calculus",
		Section: "overall",
		Detail: "",
		tier_seventy_two: 4,
		Other: 0,
		Low: 54,
		tier_sixty_four: 1,
		id: 3798,
		tier_sixty_eight: 3,
		tier_zero: 0,
		tier_seventy_six: 0,
		tier_thirty: 0,
		tier_fifty: 3,
		Professor: "",
		Audit: 0,
		tier_g_fifty: 0,
		tier_forty: 0,
		Withdrew: 1,
		Year: "2011",
		tier_twenty: 0,
		Stddev: 13.09,
		Enrolled: 35,
		tier_fifty_five: 1,
		tier_eighty: 9,
		tier_sixty: 0,
		tier_ten: 0,
		High: 100,
		Course: "120",
		Session: "w",
		Pass: 34,
		Fail: 0,
		Avg: 79.71,
		Campus: "ubc",
		Subject: "math",
	},
	{
		tier_eighty_five: 8,
		tier_ninety: 7,
		Title: "differ calculus",
		Section: "101",
		Detail: "",
		tier_seventy_two: 3,
		Other: 0,
		Low: 56,
		tier_sixty_four: 2,
		id: 5171,
		tier_sixty_eight: 3,
		tier_zero: 0,
		tier_seventy_six: 2,
		tier_thirty: 0,
		tier_fifty: 0,
		Professor: "angel, omer",
		Audit: 0,
		tier_g_fifty: 0,
		tier_forty: 0,
		Withdrew: 1,
		Year: "2009",
		tier_twenty: 0,
		Stddev: 10.57,
		Enrolled: 30,
		tier_fifty_five: 1,
		tier_eighty: 3,
		tier_sixty: 0,
		tier_ten: 0,
		High: 96,
		Course: "120",
		Session: "w",
		Pass: 29,
		Fail: 0,
		Avg: 80.79,
		Campus: "ubc",
		Subject: "math",
	},
	{
		tier_eighty_five: 8,
		tier_ninety: 7,
		Title: "differ calculus",
		Section: "overall",
		Detail: "",
		tier_seventy_two: 3,
		Other: 0,
		Low: 56,
		tier_sixty_four: 3,
		id: 5172,
		tier_sixty_eight: 3,
		tier_zero: 0,
		tier_seventy_six: 2,
		tier_thirty: 0,
		tier_fifty: 0,
		Professor: "",
		Audit: 0,
		tier_g_fifty: 0,
		tier_forty: 0,
		Withdrew: 1,
		Year: "2009",
		tier_twenty: 0,
		Stddev: 10.78,
		Enrolled: 31,
		tier_fifty_five: 1,
		tier_eighty: 3,
		tier_sixty: 0,
		tier_ten: 0,
		High: 96,
		Course: "120",
		Session: "w",
		Pass: 30,
		Fail: 0,
		Avg: 80.27,
		Campus: "ubc",
		Subject: "math",
	},
	{
		tier_eighty_five: 5,
		tier_ninety: 6,
		Title: "differ calculus",
		Section: "101",
		Detail: "",
		tier_seventy_two: 3,
		Other: 0,
		Low: 51,
		tier_sixty_four: 2,
		id: 13720,
		tier_sixty_eight: 4,
		tier_zero: 0,
		tier_seventy_six: 3,
		tier_thirty: 0,
		tier_fifty: 1,
		Professor: "gustafson, stephen james",
		Audit: 0,
		tier_g_fifty: 0,
		tier_forty: 0,
		Withdrew: 1,
		Year: "2007",
		tier_twenty: 0,
		Stddev: 12.27,
		Enrolled: 35,
		tier_fifty_five: 2,
		tier_eighty: 8,
		tier_sixty: 0,
		tier_ten: 0,
		High: 100,
		Course: "120",
		Session: "w",
		Pass: 34,
		Fail: 0,
		Avg: 79.32,
		Campus: "ubc",
		Subject: "math",
	},
	{
		tier_eighty_five: 5,
		tier_ninety: 6,
		Title: "differ calculus",
		Section: "overall",
		Detail: "",
		tier_seventy_two: 3,
		Other: 0,
		Low: 51,
		tier_sixty_four: 2,
		id: 13721,
		tier_sixty_eight: 4,
		tier_zero: 0,
		tier_seventy_six: 3,
		tier_thirty: 0,
		tier_fifty: 1,
		Professor: "",
		Audit: 0,
		tier_g_fifty: 0,
		tier_forty: 0,
		Withdrew: 1,
		Year: "2007",
		tier_twenty: 0,
		Stddev: 12.27,
		Enrolled: 35,
		tier_fifty_five: 2,
		tier_eighty: 8,
		tier_sixty: 0,
		tier_ten: 0,
		High: 100,
		Course: "120",
		Session: "w",
		Pass: 34,
		Fail: 0,
		Avg: 79.32,
		Campus: "ubc",
		Subject: "math",
	},
	{
		tier_eighty_five: 3,
		tier_ninety: 8,
		Title: "differ calculus",
		Section: "101",
		Detail: "",
		tier_seventy_two: 2,
		Other: 0,
		Low: 18,
		tier_sixty_four: 1,
		id: 27258,
		tier_sixty_eight: 2,
		tier_zero: 0,
		tier_seventy_six: 0,
		tier_thirty: 0,
		tier_fifty: 1,
		Professor: "feldman, joel",
		Audit: 0,
		tier_g_fifty: 2,
		tier_forty: 1,
		Withdrew: 0,
		Year: "2012",
		tier_twenty: 0,
		Stddev: 19.84,
		Enrolled: 26,
		tier_fifty_five: 0,
		tier_eighty: 5,
		tier_sixty: 2,
		tier_ten: 1,
		High: 100,
		Course: "120",
		Session: "w",
		Pass: 24,
		Fail: 2,
		Avg: 78.31,
		Campus: "ubc",
		Subject: "math",
	},
	*/
];
